### PR TITLE
feature: configurable TTL config option

### LINKED ISSUE #89: Reduce or allow configuration of record TTL
**Is your feature request related to a problem? Please describe.**
Potentially, a problem could arise from a < 5 min gap in service availability between IP changes

**Describe the solution you'd like**
Lower record TTL to 1 minute or (preferably) allow configurable record TTL using the JSON config file

**Describe alternatives you've considered**
Manually changing TTL in cloudflare, but I believe the script will overwrite it each time

The current record TTL is hardcoded at 300 seconds, or 5 minutes. This means services could potentially be unavailable for up to 5 minutes between IP changes. I suggest a configuration option is added to allow configurable TTL, to support use cases where a higher or lower TTL would be more appropriate.

### PR DESCRIPTION
**Pull request by Technoguyfication**
Closes #89 

Added code and updated readme + example config.

Let me know if there are any questions!

### CODE REVIEW

**Comment by Technoguyfication** [comment]
Bumping this @timothymiller 

Can you take a look at this PR when you get a chance? Thank you!

**Comment by favonia** [comment]
FYI: number 1 is a good value for Cloudflare, which means "automatic".

**Comment by Technoguyfication** [comment]
> FYI: number 1 is a good value for Cloudflare, which means "automatic".

Thanks for the insight. I'll play around with it and update the PR!

**Comment by timothymiller** [comment]
[This feature](https://github.com/timothymiller/cloudflare-ddns/commits/master) has been added, along side links to relevant documentation. By default, proxied entries, otherwise known as automatic, have a TTL of 300 seconds.

**Pull request closed without merging**
