### PR TITLE
[feature] Support for environmental substitution in config.json 

### PR DESCRIPTION
**Pull request by arulrajnet**
This PR has

- support for environmental substitution in config.json using python Template. Refer comment in #35
- Allow to run the scripts from root/any folder. For ex `./scripts/docker-build.sh`

### CODE REVIEW

**Comment by arulrajnet** [comment]
@timothymiller tested the same in my setup 
https://github.com/arulrajnet/tamilillam.arulraj.net/blob/main/docker-compose.yml
https://github.com/arulrajnet/tamilillam.arulraj.net/blob/main/conf/ddns/config.json

**Comment by arulrajnet** [comment]
@timothymiller Is there anything I am missing to merge this PR?

**Comment by andrp92** [comment]
👀

**Comment by timothymiller** [comment]
┻━┻︵ \(°□°)/ ︵ ┻━┻
Merging PRs tomorrow

**Comment by timothymiller** [comment]
Very cool @arulrajnet! Can you update this PR so the feature works as an either or.

Example: If environment variables are defined, then skip parsing `config.json`

I'd like to keep backwards compatibility for users of the existing `config.json` method.

**Comment by timothymiller** [comment]
I merged a few other PRs, one that added support for extracting IP from the network interface, instead of an HTTP request to Cloudflare. Would you mind syncing up with the master branch?

**Comment by arulrajnet** [comment]
@timothymiller Addressed all the comments. 

* skip parsing config.json if the environment variables are defined
* Sync with master.

**Comment by arulrajnet** [comment]
@timothymiller could you review again?

**Comment by yorickdowne** [comment]
This is a pretty big deal for me, this'd allow me to not bind-mount config.json, and instead do all config via env variables. 

A second PR could have a default config.json that can be overridden via bind mount.

**Comment by shaunbharat** [comment]
> This is a pretty big deal for me, this'd allow me to not bind-mount config.json, and instead do all config via env variables.
> 
> A second PR could have a default config.json that can be overridden via bind mount.

Environment variables would also simplify things in my situation.

@timothymiller, I wanted to bring your attention back to this PR because it would be beneficial to my current home lab configuration. Is there any update on if/when this PR can be merged? Thanks!

**Comment by Bamph-One** [comment]
@timothymiller This would be an extremely helpful PR to merge! Thanks

**Comment by timothymiller** [comment]
Approved!

**Comment by Bamph-One** [comment]
> Approved!

amazing! thanks Timothymiller and thanks arulrajnet!!!

**Pull request merged**
