### PR TITLE
Stop removing other DNS entries (#47)

### PR DESCRIPTION
**Pull request by zmilonas**
Hey I want to help speed up the removal of the entries and make it disabled for now.

Maybe later we can bring it back behind a feature flag (config entry)?

For now I think it would be beneficial to make sure there is no deletion as the issue suggested as it's also not documented well i think and it's potentially very destructive.

### CODE REVIEW

**Comment by skl** [comment]
+1 all my A records just got wiped

**Comment by ForsakenHarmony** [comment]
@zmilonas any chance you'll publish this as a docker image in the meantime? (arm pls)
@timothymiller pls merge 🙃

**Comment by omeganot** [comment]
Thanks for the link, @ForsakenHarmony - I saw the note here as well as by @matbor in https://github.com/timothymiller/cloudflare-ddns/issues/47 about tucking the removal code behind a config entry and figured I'd give it a shot.

**Comment by timothymiller** [comment]
Thank you @zmilonas, I approved @omeganot's PR, which I understand supercedes this in functionality. I approved [your other PR](https://github.com/timothymiller/cloudflare-ddns/pull/53)

**Pull request closed without merging**
