### PR TITLE
Fix issue #91

### PR DESCRIPTION
**Pull request by notssh**
Fix issue #91

### CODE REVIEW

**Comment by varl** [comment]
I tried this on my server and it works for me, thanks !

**Comment by gabryelreyes** [comment]
Works perfectly, Thank you!

**Comment by txhx38** [comment]
When will this be merged and pushed to the docker registry?

**Comment by timothymiller** [comment]
> When will this be merged and pushed to the docker registry?

After I have appropriate time to conduct a security review.

**Comment by notssh** [comment]
Sorry, I made a mistake. I will open a new request to another branch.

**Pull request closed without merging**
