### PR TITLE
Add a flag to modify config.json location

### PR DESCRIPTION
**Pull request by bjackman**
On Kubernetes, it's really awkward to write a Secret into the root directory:

https://www.jeffgeerling.com/blog/2019/mounting-kubernetes-secret-single-file-inside-pod

Therefore this adds support for reading the config from an arbitrary path. The
behaviour is unchanged if you don't set this new flag.

### CODE REVIEW

**Comment by timothymiller** [comment]
You can change the config.json file path today using Docker volumes.

This pr adds the ability to specify the config file path (not values) using Kubernetes Secrets, correct?

Before I approve, do you know if you can use the Kubernetes equivalent of volumes instead?

**Comment by timothymiller** [comment]
At first, I was hesitant to approve the `argparse` dependency, but after consideration I've decided that code readability & maintainability supersede docker image size.

**Comment by timothymiller** [comment]
This PR breaks backwards compatibility. Please ensure backwards compatibility before making a PR.

**Comment by bjackman** [comment]
Hey sorry I totally missed the notifications until now.

Kubernetes can indeed use volumes - how would you change the config.json
path using them?

What's the backwards compatibility issue? I can take a look if it's not
already fixed.

**Comment by bjackman** [comment]
Ah I see https://github.com/timothymiller/cloudflare-ddns/issues/40 now. I'll send a fixed version.

**Pull request merged**
