### PR TITLE
 Add a flag to modify config.json location (v2)

### PR DESCRIPTION
**Pull request by bjackman**
Same as https://github.com/timothymiller/cloudflare-ddns/pull/39 but without the bug that caused https://github.com/timothymiller/cloudflare-ddns/issues/40

This version uses action="store_true" instead of the erroneous type=bool, in
order to avoid #40

### CODE REVIEW

**Comment by bjackman** [comment]
BTW there are some other potential improvements in my fork, I didn't send them as PRs yet because I didn't wanna hit you with parallel reviews all at once, but I can do so if you'd like: https://github.com/bjackman/cloudflare-ddns/commits/master

**Comment by timothymiller** [comment]
It looks like you've been busy! I like the changes you made in your master branch. I'm looking forward to approving them into the main branch.

**Comment by timothymiller** [comment]
> BTW there are some other potential improvements in my fork, I didn't send them as PRs yet because I didn't wanna hit you with parallel reviews all at once, but I can do so if you'd like: https://github.com/bjackman/cloudflare-ddns/commits/master

Please make a PR with all your changes. They all look good, & I will test them all at once.

**Comment by timothymiller** [comment]
I reviewed your fork of cloudflare-ddns & refactored some of your work into the latest commit [#87](https://github.com/timothymiller/cloudflare-ddns/commit/55b705072a8ca2220d01422dd4e6cd72b183b833)

I cannot approve this current PR because it breaks backwards compatibility with passing in a config.json file, which is the preferred method for Docker-compose & the legacy Python script method.

**Comment by bjackman** [comment]
What's the compatibility issue here? The behaviour is the same as before if you don't pass the flag - it's default value is the same as the current behaviour.

> I reviewed your fork of cloudflare-ddns & refactored some of your work into the latest commit #87

Thanks :) FYI in doing so you discarded the authorship info which means I am not credited. In future when applying other people's patches I'd recommend either just using commands like `git cherry-pick` and `git rebase -i`, or if you apply the changes manually then use `git commit --author="John Doe <john.doe@example.com>"`

**Comment by timothymiller** [comment]
Thanks for your work so far.

This PR needs to be synced with the latest master branch to be approved.

**Comment by timothymiller** [comment]
Closing this PR as part of a yearly code cleanup

**Pull request closed without merging**
