### PR TITLE
Add healthchecks integration

### PR DESCRIPTION
**Pull request by dcasado**

### CODE REVIEW

**Comment by dcasado** [comment]
I did not intended to do this PR

**Comment by timothymiller** [comment]
You deleted my feature graphic in your fork?! 😤

I will never approve a PR with those circumstances. 😂

**Comment by dcasado** [comment]
The art is awesome! But with all the changes that I made I felt like I was stealing it.

**Comment by alangrainger** [comment]
For anyone else searching for how to add a healthcheck, here's how to do it.

Add this script `healthcheck.sh` to the same folder as your `docker-compose.yml`:

```bash
#!/bin/sh

# Check to see if the script is running
if ! ps ax | grep [c]loudflare-ddns > /dev/null 2>&1; then
    echo "cloudflare-ddns process not found. Exiting."
    exit 1
fi

# Get the remote IP from Cloudflare debugging page
local_ip=$(wget -qO - https://www.cloudflare.com/cdn-cgi/trace | grep '^ip=' | cut -d= -f2)

# Get the IP address for one of our DDNS URLs
remote_ip=$(ping -c 1 YOUR.WEBSITE.HERE | sed -nr 's/.*\((.*)\).*/\1/p')

# Compare the two IP addresses
if [[ "$remote_ip" = "$local_ip" ]]; then
    echo "DDNS address is correct: $local_ip"
else
    echo "The IP addresses do not match:"
    echo "Local IP: $local_ip"
    echo "Cloudflare IP: $remote_ip"
    exit 1
fi

```

Then update your `docker-compose.yml` to add the healthcheck:

```yaml
    volumes:
      - ./healthcheck.sh:/healthcheck.sh
    healthcheck:
      test: /healthcheck.sh
      interval: 5m
      retries: 1
      start_period: 20s
      timeout: 10s
```

**Pull request closed without merging**
